# Final Report

Refer : [Collab Notbook](https://drive.google.com/file/d/1ZFqDQ5EwdKpeMrYT3VPdAL2A9DIu_Gya/view?usp=sharing)

## Executive Summary
This report consolidates the current project assets, summarizes notebook coverage, and highlights model performance from the latest stored metrics. It is intended as a professional handoff for stakeholders and future contributors.

In [1]:
from pathlib import Path
import json
import pandas as pd

root = Path("..").resolve()
data_path = root / "datasets" / "dataset_traffic_accident_prediction1.csv"
metrics_csv = root / "results" / "model_metrics.csv"

df = pd.read_csv(data_path)
missing_by_col = df.isna().sum()
metrics = pd.read_csv(metrics_csv, index_col=0)
best_model = metrics.sort_values("f1_score", ascending=False).head(1)

notebooks = [
    {"notebook": "01_Preprocessing.ipynb", "purpose": "Data cleaning and missing value handling"},
    {"notebook": "02_EDA.ipynb", "purpose": "Exploratory data analysis"},
    {"notebook": "03_Feature_Engineering.ipynb", "purpose": "Encoding, scaling, and feature prep"},
    {"notebook": "04_Model_Training.ipynb", "purpose": "Train baseline models"},
    {"notebook": "05_Model_Evaluation.ipynb", "purpose": "Compare models and metrics"},
    {"notebook": "07_Final_Report.ipynb", "purpose": "Summary and documentation"},
]
notebook_df = pd.DataFrame(notebooks)

print("Dataset shape:", df.shape)
display(pd.DataFrame({"missing_values": missing_by_col}).T)
display(metrics)
display(best_model)
display(notebook_df)

Dataset shape: (840, 14)

,Weather,Road_Type,Time_of_Day,Traffic_Density,Speed_Limit,Number_of_Vehicles,Driver_Alcohol,Accident_Severity,Road_Condition,Vehicle_Type,Driver_Age,Driver_Experience,Road_Light_Condition,Accident
missing_values,42,42,42,42,42,42,42,42,42,42,42,42,42,42

                accuracy  precision    recall  f1_score
logistic_model  0.650407   0.427711  0.676190  0.523985
tree_model      0.940379   0.848739  0.961905  0.901786

            accuracy  precision    recall  f1_score
tree_model  0.940379   0.848739  0.961905  0.901786

                       notebook                                   purpose
0        01_Preprocessing.ipynb  Data cleaning and missing value handling
1                  02_EDA.ipynb                 Exploratory data analysis
2  03_Feature_Engineering.ipynb       Encoding, scaling, and feature prep
3       04_Model_Training.ipynb                     Train baseline models
4     05_Model_Evaluation.ipynb                Compare models and metrics
5         07_Final_Report.ipynb                 Summary and documentation